version: '3.8'
services:
  web:
    build:
      context: .
      target: development
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - go_cache:/root/.cache/go-build
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Passw0rd
      POSTGRES_DB: db

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1025:1025" # SMTP
      - "1080:1080" # Web Interface

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  go_cache:
  db_data:
