// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: create_tweet.sql

package db

import (
	"context"
)

const createTweet = `-- name: CreateTweet :one
INSERT INTO tweets (user_id, text) VALUES ($1, $2) RETURNING id, user_id, text, created_at
`

type CreateTweetParams struct {
	UserID int32
	Text   string
}

func (q *Queries) CreateTweet(ctx context.Context, arg CreateTweetParams) (Tweet, error) {
	row := q.db.QueryRowContext(ctx, createTweet, arg.UserID, arg.Text)
	var i Tweet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}
