// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: get_tweets.sql

package db

import (
	"context"
)

const getTweetsByUserId = `-- name: GetTweetsByUserId :many
SELECT id, user_id, text, created_at FROM tweets WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetTweetsByUserIdParams struct {
	UserID int32
	Limit  int32
	Offset int32
}

func (q *Queries) GetTweetsByUserId(ctx context.Context, arg GetTweetsByUserIdParams) ([]Tweet, error) {
	rows, err := q.db.QueryContext(ctx, getTweetsByUserId, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tweet
	for rows.Next() {
		var i Tweet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
