// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"database/sql"
)

type Tweet struct {
	ID        int32
	UserID    int32
	Text      string
	CreatedAt sql.NullTime
}

type User struct {
	ID              int32
	Email           string
	PasswordHash    string
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	IsActive        sql.NullBool
	ActivationToken sql.NullString
}
